alias ..='cd ..'
alias apt-get='sudo apt-get'
alias distro='lsb_release -a'
alias grep='grep --color=auto'
alias mkdir='mkdir -pv'
alias diff='colordiff'
alias ports='netstat -tulnp'
alias conns='netstat -tnp'
alias disk='df -h'
